version: "3.8"

networks:
  mapeditor-net:
    external:
      name: mapeditor-net

volumes:
  validator-storage:

services:
  mapeditor:
    container_name: esdl-mapeditor
    image: esdlmapeditoressim/esdl-mapeditor:latest
    volumes:
      - "./esdl-mapeditor/client_secrets_opensource.json:/usr/src/app/credentials/client_secrets_opensource.json"
    networks:
      - mapeditor-net
    ports:
      - "${MAPEDITOR_PORT:-8111}:8111"
    env_file:
      - mapeditor_open_source.env

  boundary-service:
    container_name: boundary-service
    image: esdlmapeditoressim/boundary-service:latest
    networks:
      - mapeditor-net
    ports:
      - "${BOUNDARYSERVICE_PORT:-4002}:4002"
    env_file:
      - boundary_service.env

  panel-service:
    container_name: panel-service
    image: esdlmapeditoressim/panel-service:latest
    # image: panel-service:latest
    ports:
      - 3400:5000
    networks:
      - mapeditor-net
    environment:
      - ENV=dev
      - INTERNAL_GRAFANA_HOST=grafana
      - INTERNAL_GRAFANA_PORT=3000
      - EXTERNAL_GRAFANA_URL=http://localhost:3000
    env_file:
      - panel_service.env

  esdl-validator:
    image: mvrijlandt/nwn_esdl_validator:0.0.3
    ports:
      - "5000:5000"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - validator-storage:/storage
    networks:
      - mapeditor-net
